version: '2'

services:
  realtime_server:
    image: docker-frontend:latest
    ports:
      - "8086:80"

  kafka_stream_server:
    image: docker-streaming:latest
    ports:
      - "8002:80"

  kafka_producer_server:
    image: docker-log-creator:latest
    ports:
      - "8085:80"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "data-in,data-out"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181